def get_texts():
    return {
        "tr": {
            "welcome_title": "🚀 Ziyaretçi Girişi",
            "welcome_subtitle": "Sohbete başlamadan önce sizi tanımak isterim.",
            "welcome_subtitle": "Sohbete başlamadan önce sizi tanımak isterim.",
            "profile_title": "Dijital İkiz",
            "profile_role": "İnteraktif Portfolyo",
            "profile_location": "v1.1",
            "skills_title": "Teknolojiler ve Yetenekler",
            "skills_list": ["Gemini 2.5 Flash", "Prompt Engineering", "Streamlit", "Python"],
            "profile_desc": "\nBu proje, Kerem Kundak'ın profesyonel geçmişini interaktif bir şekilde sunmak için geliştirilmiş bir **Yapay Zeka Asistanıdır**.",
            "input_name": "Adınız Soyadınız (İsteğe Bağlı)",
            "input_company": "Şirket Adı (İsteğe Bağlı)",
            "input_email": "E-posta (İsteğe Bağlı)",
            "btn_read_kvkk": "📜 Aydınlatma Metnini Oku",
            "kvkk_status_ok": "✅ Onaylandı",
            "kvkk_status_wait": "⚠️ Bekleniyor",
            "chk_consent": "Metni okudum, verilerimin işlenmesini kabul ediyorum.",
            "btn_start": "Sohbete Başla ✨",
            "err_kvkk": "Lütfen aydınlatma metnini okuyup onaylayın.",
            "err_missing_info": "Lütfen İsim ve E-posta alanlarını doldurun.",
            "login_success": "Giriş yapılıyor...",
            "user_anon": "Anonim Ziyaretçi",
            "user_unknown_company": "Belirtilmedi",
            "sidebar_user_title": "👤 Ziyaretçi Profili",
            "sidebar_download": "📄 CV'yi İndir",
            "btn_exit": "Bitir ve Çık",
            "chat_placeholder": "Kerem hakkında bir soru sorun...",
            "ai_thinking": "Yazıyor...",
            "kvkk_modal_title": "📜 Aydınlatma Metni",
            "kvkk_modal_body": """
            **1. Veri Sorumlusu:** Bu uygulama Kerem Kundak tarafından geliştirilmiştir.\n
            **2. Amaç:** Geliştirme amaçlı, sohbet geçmişini depolamak.\n
            **3. Haklarınız:** İsimle girişlerde keremkundak@gmail.com adresinden iletişime geçerek verilerinizi silme hakkınız vardır.\n
            **Önemli:** Anonim girişlerde verinin kime ait olduğu tespit edilemediğinden silme talepleri karşılanamamaktadır.\n
            """,
            "kvkk_modal_btn": "Okudum ve Anladım ✅",
            "mail_subject_transcript": "✅ Sohbet Özeti",
            "mail_subject_timeout": "⏳ Sohbet Özeti (Zaman Aşımı)",
            "prompt_role": "Sen Kerem'in Dijital İkizisin. Sorulara BİRİNCİ TEKİL ŞAHIS ('Ben') ile TÜRKÇE cevap ver.",
            "ex_btn_1": "🎓 Eğitim Geçmişin Nedir?",
            "ex_btn_2": "🚀 Hangi Projeleri Yaptın?",
            "ex_btn_3": "🛠️ Teknik Yeteneklerin Neler?",
            "ai_disclaimer": "⚠️ Yapay zeka hata yapabilir. Lütfen önemli bilgileri teyit ediniz.",
            "btn_linkedin": "www.linkedin.com/in/kerem-kundak",
            "btn_github": "www.github.com/keremkundak",
            "welcome_chat": "Merhaba {name}! 👋 Ben Kerem'in Dijital İkiziyim. Kerem'in profesyonel geçmişi, yetenekleri ve projeleri hakkında her şeyi bana sorabilirsin. Nasıl yardımcı olabilirim?",
            "btn_guest": "🕵️ Anonim Giriş Yap",
            "guest_name": "Anonim Ziyaretçi",
            "guest_info": "ℹ️ Anonim girişlerde kişisel verileriniz (isim, e-posta) saklanmaz, sadece sohbet geçmişi kalite amaçlı tutulur."
        },
        "en": {
            "welcome_title": "🚀 Visitor Login",
            "welcome_subtitle": "I'd like to get to know you before we start.",
            "welcome_subtitle": "I'd like to get to know you before we start.",
            "profile_title": "Digital Twin",
            "profile_role": "Interactive Portfolio",
            "profile_location": "v1.1",
            "skills_title": "Technologies and Skills",
            "skills_list": ["Gemini 2.5 Flash", "Prompt Engineering", "Streamlit", "Python"],
            "profile_desc": "\nThis project is an **AI Assistant** developed to interactively present Kerem Kundak's professional background.",
            "input_name": "Full Name",
            "input_company": "Company Name",
            "input_email": "Email Address",
            "btn_read_kvkk": "📜 Read Privacy Policy",
            "kvkk_status_ok": "✅ Approved",
            "kvkk_status_wait": "⚠️ Pending",
            "chk_consent": "I have read the text and agree to data processing.",
            "btn_start": "Start Chat ✨",
            "err_kvkk": "Please check 'I have read the text and agree to data processing' checkbox first.",
            "err_missing_info": "Please fill in Name and Email fields.",
            "login_success": "Logging in...",
            "user_anon": "Anonymous Visitor",
            "user_unknown_company": "Not Specified",
            "sidebar_user_title": "👤 Visitor Profile",
            "sidebar_download": "📄 Download CV",
            "btn_exit": "End & Exit",
            "chat_placeholder": "Ask a question about Kerem...",
            "ai_thinking": "Typing...",
            "kvkk_modal_title": "📜 Privacy Policy",
            "kvkk_modal_body": """
            **1. Data Controller:** Developed by Kerem Kundak.\n
            **2. Purpose:** To store chat transcripts for further development.\n
            **3. Your Rights:** You have the right to request deletion for named logins from keremkundak@gmail.com.\n
            **Important:** For anonymous logins, deletion requests cannot be fulfilled as ownership cannot be verified.\n
            """,
            "kvkk_modal_btn": "Read and Understood ✅",
            "mail_subject_transcript": "✅ Chat Transcript",
            "mail_subject_timeout": "⏳ Chat Transcript (Timeout)",
            "prompt_role": "You are Kerem's Digital Twin. Answer questions in FIRST PERSON ('I', 'My') in ENGLISH.",
            "ex_btn_1": "🎓 What is your education background?",
            "ex_btn_2": "🚀 What are your top projects?",
            "ex_btn_3": "🛠️ What are your technical skills?",
            "ai_disclaimer": "⚠️ AI can make mistakes. Please verify important information.",
            "btn_linkedin": "www.linkedin.com/in/kerem-kundak",
            "btn_github": "www.github.com/keremkundak",
            "welcome_chat": "Hello {name}! 👋 I am Kerem's Digital Twin. You can ask me anything about Kerem's professional background, skills, and projects. How can I help you?",
            "btn_guest": "🕵️ Login Anonymously",
            "guest_name": "Anonymous Visitor",
            "guest_info": "ℹ️ For anonymous logins, personal data (name, email) is not stored; only chat history is kept for quality purposes."
        }
    }